# GitHub Actions Workflow responsible for cleaning up the WXT React Template repository from the template-specific files and configurations.
# This workflow is supposed to be triggered automatically when a new template-based repository has been created.

name: Template Cleanup

on:
  push:
    branches: [main]

jobs:
  # Run a cleaning process only if the workflow is triggered by the non-"node-cli-template" repository.
  template-cleanup:
    name: Template Cleanup
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'node-cli-template'
    permissions:
      contents: write
    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v4

      # Cleanup project
      - name: Cleanup
        uses: ryohidaka/nodejs-cleanup@v1.1.3
        with:
          description: ''
          excluded: 'CHANGELOG, .github/FUNDING.yml, .github/workflows/template-cleanup.yml'
          template-dir: '.github/template'
          remove-template-dir: true
